#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dec0de.UI.HashLoader.EmbeddedDal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhoneDecode")]
	public partial class PhoneDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PhoneDbDataContext() : 
				base(global::Dec0de.UI.Properties.Settings.Default.PhoneDecodeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_HashRun_Insert")]
		public ISingleResult<usp_HashRun_InsertResult> usp_HashRun_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string memoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slideAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> blocksizeBytes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> numBlocks, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> timeToHashSeconds, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string hashType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string notes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateTime, phoneId, memoryId, slideAmount, blocksizeBytes, numBlocks, timeToHashSeconds, hashType, notes);
			return ((ISingleResult<usp_HashRun_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_HashRun_Update")]
		public int usp_HashRun_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hashRunId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numBlocks, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> timeToHashSeconds)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hashRunId, numBlocks, timeToHashSeconds);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Phone_Insert")]
		public ISingleResult<usp_Phone_InsertResult> usp_Phone_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string make, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string model, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string subId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string notes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), make, model, subId, notes);
			return ((ISingleResult<usp_Phone_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Phoneid_GetByMemoryid")]
		public ISingleResult<usp_Phoneid_GetByMemoryidResult> usp_Phoneid_GetByMemoryid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string memoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> blocksize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slideAmount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), memoryId, blocksize, slideAmount);
			return ((ISingleResult<usp_Phoneid_GetByMemoryidResult>)(result.ReturnValue));
		}
	}
	
	public partial class usp_HashRun_InsertResult
	{
		
		private int _hashRunId;
		
		public usp_HashRun_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hashRunId", DbType="Int NOT NULL")]
		public int hashRunId
		{
			get
			{
				return this._hashRunId;
			}
			set
			{
				if ((this._hashRunId != value))
				{
					this._hashRunId = value;
				}
			}
		}
	}
	
	public partial class usp_Phone_InsertResult
	{
		
		private int _phoneId;
		
		public usp_Phone_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneId", DbType="Int NOT NULL")]
		public int phoneId
		{
			get
			{
				return this._phoneId;
			}
			set
			{
				if ((this._phoneId != value))
				{
					this._phoneId = value;
				}
			}
		}
	}
	
	public partial class usp_Phoneid_GetByMemoryidResult
	{
		
		private int _phoneId;
		
		public usp_Phoneid_GetByMemoryidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneId", DbType="Int NOT NULL")]
		public int phoneId
		{
			get
			{
				return this._phoneId;
			}
			set
			{
				if ((this._phoneId != value))
				{
					this._phoneId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
