#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dec0de.Bll.EmbeddedDal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhoneDecode")]
	public partial class PhoneDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PhoneDbDataContext() : 
				base(global::Dec0de.Bll.Properties.Settings.Default.PhoneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhoneDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_Insert")]
		public int usp_ParsedFields_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> offset, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string hex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string printable)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, offset, name, hex, printable);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedPhoneNum_Insert")]
		public int usp_ParsedPhoneNum_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string areaCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, number, sevenDigit, areaCode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedPhoneNum_AutoUpdate")]
		public int usp_ParsedPhoneNum_AutoUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Answers_PhoneNum_Insert")]
		public int usp_Answers_PhoneNum_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string areaCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phoneId, number, sevenDigit, areaCode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Parse_Insert")]
		public ISingleResult<usp_Parse_InsertResult> usp_Parse_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeUdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string memoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> blockSizeBytes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slideAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> bytesFiltered, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> bytesNotFiltered, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> filterTimeSeconds, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> viterbiTimeSeconds, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string notes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), timeUdt, phoneId, memoryId, blockSizeBytes, slideAmount, bytesFiltered, bytesNotFiltered, filterTimeSeconds, viterbiTimeSeconds, notes);
			return ((ISingleResult<usp_Parse_InsertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_GetByParseId")]
		public ISingleResult<usp_ParsedFields_GetByParseIdResult> usp_ParsedFields_GetByParseId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_ParsedFields_GetByParseIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Hash_GetByPhoneId")]
		public ISingleResult<usp_Hash_GetByPhoneIdResult> usp_Hash_GetByPhoneId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> blocksize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slideAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string memoryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), blocksize, slideAmount, phoneId, memoryId);
			return ((ISingleResult<usp_Hash_GetByPhoneIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Answers_AddressBook_Insert")]
		public int usp_Answers_AddressBook_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string source)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phoneId, name, number, sevenDigit, source);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Answers_CallLog_Insert")]
		public int usp_Answers_CallLog_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeStamp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string source)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phoneId, name, number, sevenDigit, type, timeStamp, source);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Answers_SMS_Insert")]
		public int usp_Answers_SMS_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeStamp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string source)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phoneId, name, number, sevenDigit, timeStamp, message, source);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_GetAllRecordPhoneNumbers_ByParseId")]
		public ISingleResult<usp_ParsedFields_GetAllRecordPhoneNumbers_ByParseIdResult> usp_ParsedFields_GetAllRecordPhoneNumbers_ByParseId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_ParsedFields_GetAllRecordPhoneNumbers_ByParseIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_GetAllRecordPhoneNumbersWithRecordType_ByParseId")]
		public ISingleResult<usp_ParsedFields_GetAllRecordPhoneNumbersWithRecordType_ByParseIdResult> usp_ParsedFields_GetAllRecordPhoneNumbersWithRecordType_ByParseId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_ParsedFields_GetAllRecordPhoneNumbersWithRecordType_ByParseIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Feature_AddressBook_Insert")]
		public int usp_Feature_AddressBook_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> areaCodeScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> phoneCrossScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> phoneFormScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> lengthScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> alphaScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> bigramScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isTruePositive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, name, number, areaCodeScore, phoneCrossScore, phoneFormScore, lengthScore, alphaScore, bigramScore, isTruePositive);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Feature_AddressBook_GetByParseId")]
		public ISingleResult<usp_Feature_AddressBook_GetByParseIdResult> usp_Feature_AddressBook_GetByParseId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_Feature_AddressBook_GetByParseIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_AddressBook_GetFalsePositivesByParseId")]
		public ISingleResult<usp_ParsedFields_AddressBook_GetFalsePositivesByParseIdResult> usp_ParsedFields_AddressBook_GetFalsePositivesByParseId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_ParsedFields_AddressBook_GetFalsePositivesByParseIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_AddressBook_Insert")]
		public int usp_ParsedFields_AddressBook_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> offset)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, name, number, sevenDigit, offset);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_CallLog_Insert")]
		public int usp_ParsedFields_CallLog_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeStamp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> offset)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, name, number, sevenDigit, type, timeStamp, offset);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Decode_CallLogs_CompareAnswersToParse")]
		public ISingleResult<usp_Decode_CallLogs_CompareAnswersToParseResult> usp_Decode_CallLogs_CompareAnswersToParse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_Decode_CallLogs_CompareAnswersToParseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Feature_Calllog_Insert")]
		public int usp_Feature_Calllog_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timestamp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> areaCodeScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> phoneCrossScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> phoneFormScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> lengthScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> alphaScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> bigramScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> dateDist, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isTruePositive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, name, number, timestamp, areaCodeScore, phoneCrossScore, phoneFormScore, lengthScore, alphaScore, bigramScore, dateDist, isTruePositive);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_SMS_Insert")]
		public int usp_ParsedFields_SMS_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string sevenDigit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sevenDigit2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeStamp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> offset)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, name, number, sevenDigit, number2, sevenDigit2, message, timeStamp, offset);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Decode_SMS_CompareAnswersToParse")]
		public ISingleResult<usp_Decode_SMS_CompareAnswersToParseResult> usp_Decode_SMS_CompareAnswersToParse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_Decode_SMS_CompareAnswersToParseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Feature_Sms_Insert")]
		public int usp_Feature_Sms_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string number2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timestamp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> areaCodeScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> phoneCrossScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> phoneFormScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> lengthScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> alphaScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> bigramScore, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> dateDist, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isTruePositive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId, name, number, number2, timestamp, message, areaCodeScore, phoneCrossScore, phoneFormScore, lengthScore, alphaScore, bigramScore, dateDist, isTruePositive);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_ParsedFields_Sms_GetFalsePositivesByParseId")]
		public ISingleResult<usp_ParsedFields_Sms_GetFalsePositivesByParseIdResult> usp_ParsedFields_Sms_GetFalsePositivesByParseId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_ParsedFields_Sms_GetFalsePositivesByParseIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Hash_GetUnfilteredBlocks")]
		public ISingleResult<usp_Hash_GetUnfilteredBlocksResult> usp_Hash_GetUnfilteredBlocks([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> blocksize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slideAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string memoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> noFilter, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slideAmountLibrary)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), blocksize, slideAmount, phoneId, memoryId, noFilter, slideAmountLibrary);
			return ((ISingleResult<usp_Hash_GetUnfilteredBlocksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Decode_AddressBook_CompareAnswersToParse")]
		public ISingleResult<usp_Decode_AddressBook_CompareAnswersToParseResult> usp_Decode_AddressBook_CompareAnswersToParse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parseId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parseId);
			return ((ISingleResult<usp_Decode_AddressBook_CompareAnswersToParseResult>)(result.ReturnValue));
		}
	}
	
	public partial class usp_Parse_InsertResult
	{
		
		private int _parseId;
		
		public usp_Parse_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int NOT NULL")]
		public int parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
	}
	
	public partial class usp_ParsedFields_GetByParseIdResult
	{
		
		private int _parseId;
		
		private long _offset;
		
		private string _name;
		
		private string _hex;
		
		private string _printable;
		
		public usp_ParsedFields_GetByParseIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int NOT NULL")]
		public int parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offset", DbType="BigInt NOT NULL")]
		public long offset
		{
			get
			{
				return this._offset;
			}
			set
			{
				if ((this._offset != value))
				{
					this._offset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hex", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string hex
		{
			get
			{
				return this._hex;
			}
			set
			{
				if ((this._hex != value))
				{
					this._hex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printable", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string printable
		{
			get
			{
				return this._printable;
			}
			set
			{
				if ((this._printable != value))
				{
					this._printable = value;
				}
			}
		}
	}
	
	public partial class usp_Hash_GetByPhoneIdResult
	{
		
		private string _hash;
		
		private long _blockindex;
		
		public usp_Hash_GetByPhoneIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hash", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string hash
		{
			get
			{
				return this._hash;
			}
			set
			{
				if ((this._hash != value))
				{
					this._hash = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blockindex", DbType="BigInt NOT NULL")]
		public long blockindex
		{
			get
			{
				return this._blockindex;
			}
			set
			{
				if ((this._blockindex != value))
				{
					this._blockindex = value;
				}
			}
		}
	}
	
	public partial class usp_ParsedFields_GetAllRecordPhoneNumbers_ByParseIdResult
	{
		
		private string _number;
		
		public usp_ParsedFields_GetAllRecordPhoneNumbers_ByParseIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
	
	public partial class usp_ParsedFields_GetAllRecordPhoneNumbersWithRecordType_ByParseIdResult
	{
		
		private string _number;
		
		private string _recordType;
		
		public usp_ParsedFields_GetAllRecordPhoneNumbersWithRecordType_ByParseIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordType", DbType="VarChar(30)")]
		public string recordType
		{
			get
			{
				return this._recordType;
			}
			set
			{
				if ((this._recordType != value))
				{
					this._recordType = value;
				}
			}
		}
	}
	
	public partial class usp_Feature_AddressBook_GetByParseIdResult
	{
		
		private int _parseId;
		
		private string _name;
		
		private string _number;
		
		private double _areaCodeScore;
		
		private double _phoneCrossScore;
		
		private double _phoneFormScore;
		
		private double _lengthScore;
		
		private double _alphaScore;
		
		private double _bigramScore;
		
		private bool _isTruePositive;
		
		public usp_Feature_AddressBook_GetByParseIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int NOT NULL")]
		public int parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCodeScore", DbType="Float NOT NULL")]
		public double areaCodeScore
		{
			get
			{
				return this._areaCodeScore;
			}
			set
			{
				if ((this._areaCodeScore != value))
				{
					this._areaCodeScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneCrossScore", DbType="Float NOT NULL")]
		public double phoneCrossScore
		{
			get
			{
				return this._phoneCrossScore;
			}
			set
			{
				if ((this._phoneCrossScore != value))
				{
					this._phoneCrossScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneFormScore", DbType="Float NOT NULL")]
		public double phoneFormScore
		{
			get
			{
				return this._phoneFormScore;
			}
			set
			{
				if ((this._phoneFormScore != value))
				{
					this._phoneFormScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lengthScore", DbType="Float NOT NULL")]
		public double lengthScore
		{
			get
			{
				return this._lengthScore;
			}
			set
			{
				if ((this._lengthScore != value))
				{
					this._lengthScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alphaScore", DbType="Float NOT NULL")]
		public double alphaScore
		{
			get
			{
				return this._alphaScore;
			}
			set
			{
				if ((this._alphaScore != value))
				{
					this._alphaScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bigramScore", DbType="Float NOT NULL")]
		public double bigramScore
		{
			get
			{
				return this._bigramScore;
			}
			set
			{
				if ((this._bigramScore != value))
				{
					this._bigramScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isTruePositive", DbType="Bit NOT NULL")]
		public bool isTruePositive
		{
			get
			{
				return this._isTruePositive;
			}
			set
			{
				if ((this._isTruePositive != value))
				{
					this._isTruePositive = value;
				}
			}
		}
	}
	
	public partial class usp_ParsedFields_AddressBook_GetFalsePositivesByParseIdResult
	{
		
		private System.Nullable<int> _phoneId;
		
		private System.Nullable<int> _parseId;
		
		private string _name;
		
		private string _number;
		
		public usp_ParsedFields_AddressBook_GetFalsePositivesByParseIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneId", DbType="Int")]
		public System.Nullable<int> phoneId
		{
			get
			{
				return this._phoneId;
			}
			set
			{
				if ((this._phoneId != value))
				{
					this._phoneId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int")]
		public System.Nullable<int> parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
	
	public partial class usp_Decode_CallLogs_CompareAnswersToParseResult
	{
		
		private System.Nullable<int> _phoneId;
		
		private System.Nullable<int> _parseId;
		
		private string _answer_name;
		
		private string _answer_number;
		
		private string _answer_sevenDigit;
		
		private System.Nullable<System.DateTime> _answer_timestamp;
		
		private string _answer_source;
		
		private string _name;
		
		private string _number;
		
		private System.Nullable<System.DateTime> _timestamp;
		
		public usp_Decode_CallLogs_CompareAnswersToParseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneId", DbType="Int")]
		public System.Nullable<int> phoneId
		{
			get
			{
				return this._phoneId;
			}
			set
			{
				if ((this._phoneId != value))
				{
					this._phoneId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int")]
		public System.Nullable<int> parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_name", DbType="VarChar(50)")]
		public string answer_name
		{
			get
			{
				return this._answer_name;
			}
			set
			{
				if ((this._answer_name != value))
				{
					this._answer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_number", DbType="VarChar(50)")]
		public string answer_number
		{
			get
			{
				return this._answer_number;
			}
			set
			{
				if ((this._answer_number != value))
				{
					this._answer_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_sevenDigit", DbType="VarChar(7)")]
		public string answer_sevenDigit
		{
			get
			{
				return this._answer_sevenDigit;
			}
			set
			{
				if ((this._answer_sevenDigit != value))
				{
					this._answer_sevenDigit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> answer_timestamp
		{
			get
			{
				return this._answer_timestamp;
			}
			set
			{
				if ((this._answer_timestamp != value))
				{
					this._answer_timestamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_source", DbType="VarChar(20)")]
		public string answer_source
		{
			get
			{
				return this._answer_source;
			}
			set
			{
				if ((this._answer_source != value))
				{
					this._answer_source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this._timestamp = value;
				}
			}
		}
	}
	
	public partial class usp_Decode_SMS_CompareAnswersToParseResult
	{
		
		private System.Nullable<int> _phoneId;
		
		private System.Nullable<int> _parseId;
		
		private string _answer_name;
		
		private string _answer_number;
		
		private string _answer_sevenDigit;
		
		private System.Nullable<System.DateTime> _answer_timestamp;
		
		private string _answer_message;
		
		private string _answer_source;
		
		private string _name;
		
		private string _number;
		
		private string _sevnDigit;
		
		private string _number2;
		
		private string _sevnDigit2;
		
		private System.Nullable<System.DateTime> _timestamp;
		
		private string _message;
		
		public usp_Decode_SMS_CompareAnswersToParseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneId", DbType="Int")]
		public System.Nullable<int> phoneId
		{
			get
			{
				return this._phoneId;
			}
			set
			{
				if ((this._phoneId != value))
				{
					this._phoneId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int")]
		public System.Nullable<int> parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_name", DbType="VarChar(50)")]
		public string answer_name
		{
			get
			{
				return this._answer_name;
			}
			set
			{
				if ((this._answer_name != value))
				{
					this._answer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_number", DbType="VarChar(50)")]
		public string answer_number
		{
			get
			{
				return this._answer_number;
			}
			set
			{
				if ((this._answer_number != value))
				{
					this._answer_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_sevenDigit", DbType="VarChar(7)")]
		public string answer_sevenDigit
		{
			get
			{
				return this._answer_sevenDigit;
			}
			set
			{
				if ((this._answer_sevenDigit != value))
				{
					this._answer_sevenDigit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> answer_timestamp
		{
			get
			{
				return this._answer_timestamp;
			}
			set
			{
				if ((this._answer_timestamp != value))
				{
					this._answer_timestamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_message", DbType="VarChar(200)")]
		public string answer_message
		{
			get
			{
				return this._answer_message;
			}
			set
			{
				if ((this._answer_message != value))
				{
					this._answer_message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_source", DbType="VarChar(20)")]
		public string answer_source
		{
			get
			{
				return this._answer_source;
			}
			set
			{
				if ((this._answer_source != value))
				{
					this._answer_source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sevnDigit", DbType="VarChar(7)")]
		public string sevnDigit
		{
			get
			{
				return this._sevnDigit;
			}
			set
			{
				if ((this._sevnDigit != value))
				{
					this._sevnDigit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number2", DbType="VarChar(50)")]
		public string number2
		{
			get
			{
				return this._number2;
			}
			set
			{
				if ((this._number2 != value))
				{
					this._number2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sevnDigit2", DbType="VarChar(7)")]
		public string sevnDigit2
		{
			get
			{
				return this._sevnDigit2;
			}
			set
			{
				if ((this._sevnDigit2 != value))
				{
					this._sevnDigit2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this._timestamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(200)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this._message = value;
				}
			}
		}
	}
	
	public partial class usp_ParsedFields_Sms_GetFalsePositivesByParseIdResult
	{
		
		private System.Nullable<int> _phoneId;
		
		private System.Nullable<int> _parseId;
		
		private string _name;
		
		private string _number;
		
		private string _number2;
		
		private System.Nullable<System.DateTime> _timeStamp;
		
		private string _message;
		
		public usp_ParsedFields_Sms_GetFalsePositivesByParseIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneId", DbType="Int")]
		public System.Nullable<int> phoneId
		{
			get
			{
				return this._phoneId;
			}
			set
			{
				if ((this._phoneId != value))
				{
					this._phoneId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int")]
		public System.Nullable<int> parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number2", DbType="VarChar(50)")]
		public string number2
		{
			get
			{
				return this._number2;
			}
			set
			{
				if ((this._number2 != value))
				{
					this._number2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> timeStamp
		{
			get
			{
				return this._timeStamp;
			}
			set
			{
				if ((this._timeStamp != value))
				{
					this._timeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(200)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this._message = value;
				}
			}
		}
	}
	
	public partial class usp_Hash_GetUnfilteredBlocksResult
	{
		
		private string _hash;
		
		private System.Nullable<long> _blockIndexFirst;
		
		public usp_Hash_GetUnfilteredBlocksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hash", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string hash
		{
			get
			{
				return this._hash;
			}
			set
			{
				if ((this._hash != value))
				{
					this._hash = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blockIndexFirst", DbType="BigInt")]
		public System.Nullable<long> blockIndexFirst
		{
			get
			{
				return this._blockIndexFirst;
			}
			set
			{
				if ((this._blockIndexFirst != value))
				{
					this._blockIndexFirst = value;
				}
			}
		}
	}
	
	public partial class usp_Decode_AddressBook_CompareAnswersToParseResult
	{
		
		private System.Nullable<int> _phoneId;
		
		private System.Nullable<int> _parseId;
		
		private string _answer_name;
		
		private string _answer_number;
		
		private string _answer_sevenDigit;
		
		private string _answer_source;
		
		private string _name;
		
		private string _number;
		
		public usp_Decode_AddressBook_CompareAnswersToParseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneId", DbType="Int")]
		public System.Nullable<int> phoneId
		{
			get
			{
				return this._phoneId;
			}
			set
			{
				if ((this._phoneId != value))
				{
					this._phoneId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parseId", DbType="Int")]
		public System.Nullable<int> parseId
		{
			get
			{
				return this._parseId;
			}
			set
			{
				if ((this._parseId != value))
				{
					this._parseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_name", DbType="VarChar(50)")]
		public string answer_name
		{
			get
			{
				return this._answer_name;
			}
			set
			{
				if ((this._answer_name != value))
				{
					this._answer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_number", DbType="VarChar(50)")]
		public string answer_number
		{
			get
			{
				return this._answer_number;
			}
			set
			{
				if ((this._answer_number != value))
				{
					this._answer_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_sevenDigit", DbType="VarChar(7)")]
		public string answer_sevenDigit
		{
			get
			{
				return this._answer_sevenDigit;
			}
			set
			{
				if ((this._answer_sevenDigit != value))
				{
					this._answer_sevenDigit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_source", DbType="VarChar(20)")]
		public string answer_source
		{
			get
			{
				return this._answer_source;
			}
			set
			{
				if ((this._answer_source != value))
				{
					this._answer_source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
